apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-istio
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "istio"
spec:
  target: control-plane
  channel: regular
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Istio
    metadata:
      name: istio-sample
      labels:
        app.kubernetes.io/name: istio-sample
    spec:
      config:
        numTrustedProxies: 1
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/istio
      provider: internal
      repositoryContexts:
      - baseUrl: ghcr.io/pbochynski/istio-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.2.0
      - access:
          digest: sha256:8bb34cfba9500c34b03c8cda417c1745360c622b4af683c2ffb72d6663435214
          type: localOciBlob
        name: istio
        relation: local
        type: helm-chart
        version: v0.2.0
      sources:
      - access:
          commit: 5cac2f91d85eb93d1a0dd8ff7d187968bbed9cb2
          repoUrl: github.com/kyma-project/istio
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        name: module-sources
        type: git
        version: v0.2.0
      version: v0.2.0
    meta:
      schemaVersion: v2
---
apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-cluster-ip
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "cluster-ip"
spec:
  target: control-plane
  channel: beta
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: ClusterIP
    metadata:
      name: clusterip-nodes
    spec:
      nodeSpreadLabel: kubernetes.io/hostname
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/cluster-ip
      provider: internal
      repositoryContexts:
      - baseUrl: ghcr.io/pbochynski/cluster-ip-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:e212eee87097e6d9784c9af08b45533ab50aa628fd61d9c03ed37569601b9405
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.0.26
      - access:
          digest: sha256:e39551956abf9efee43d160b3b9e0de4cb0696007d2f12fb10d9e03ccc07776f
          type: localOciBlob
        name: cluster-ip
        relation: local
        type: helm-chart
        version: v0.0.26
      sources:
      - access:
          commit: ae292f39a24bb9f10b5e6b0980cb5a7ff326a074
          repoUrl: github.com/kyma-project/cluster-ip
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: HEAD
          version: v1
        name: module-sources
        type: git
        version: v0.0.26
      version: v0.0.26
    meta:
      schemaVersion: v2
---
apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-keda
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "keda"
  annotations:
    "operator.kyma-project.io/module-version": "0.0.1-a0e8648"
    "operator.kyma-project.io/module-provider": "internal"
    "operator.kyma-project.io/descriptor-schema-version": "v2"
spec:
  target: control-plane
  channel: beta
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Keda
    metadata:
      name: keda-sample
      namespace: kyma-system
    spec:
      logging:
        operator:
          level: "debug"
  descriptor:
    component:
      componentReferences: []
      name: kyma.project.io/module/keda
      provider: internal
      repositoryContexts:
      - baseUrl: europe-docker.pkg.dev/kyma-project/prod/unsigned
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:86f21c6cc5d82167b10a23bb5a82e852cd5b8d6292e0ea448261c90ff6893a1a
          type: localOciBlob
        name: keda
        relation: local
        type: helm-chart
        version: 0.0.1-a0e8648
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: 0.0.1-a0e8648
      sources:
      - access:
          commit: a0e86481d91cb126972e2cba82361c11d6e4d2db
          ref: refs/heads/main
          repoUrl: github.com/kyma-project/keda-manager
          type: github
        name: keda-manager
        type: git
        version: 0.0.1-a0e8648
      version: 0.0.1-a0e8648
    meta:
      schemaVersion: v2